### ISSUE TITLE
Set good score higher than 0 (and spam score below 0)

### ISSUE THREAD

**Issue by sphh** [friedPotat0/Spam-Scores#22]
**Describe the bug**
I want to set the spam score for good emails to 2, but the preferences page does not allow me to set it above 0.

I tried to find the value in the advanced configuration screen, but only found the entry `spamscores.hello`.

(I also tried to set the spam score for junk mails to below 0, but this is also not allowed.)

**Reproduction steps**
1. Set the score for "red" emails above 0.
2. Try to set the score for "green" emails to a value above 0. This does not work (and the upwards arrow is not greyed out, but that's a minor issue.)

**Expected behavior**
I would like to be able to set the "green" score to values higher than 0.

**Thunderbird (please complete the following information):**
 - OS: Linux Mint 20.1
 - Version: 78.7.1 (64-bit)

**Spam Score add-on (please complete the following information):**
 - Version: 1.1.6

**Comment by friedPotat0** [comment]
This behaviour was actually intended. I've never thought about a use case where one would highlight non-spams as spam or the other way around. I've developed this add-on with the focus on the standardised score ranges of the most popular mail servers. When you say that you want to mark mails as spam that the server has not classified as such, it would be probably better to adjust the mail server itself.

The yellow icon is useful for any mails that are not precisely classified as spam or ham by the mail server. If I understand you correctly, you want to disable the yellow range completely, won't you? I would not recommend to do this cause of the uncertainty of the mail servers classification in the first place.

**Comment by sphh** [comment]
That's what I did: I adjusted the mail server itself! I have a standard spam-assassin running with greylisting. I only have adjusted the spam levels when an email is greylisted (level 2-5) and when it is classified as spam and rejected straight away (level >5). Hence it is pretty obvious to me, that I want the following displays:
- "green": not greylisted, hence level < 2
- "yellow": possible spam, greylisted, hence level between 2 and 5
- "red": spam, level >5

This works very well for me. You could argue, that I could (and should) lower the greylist level to 0, but I noticed that many legitimate emails have values below 2 (resulting in false - temporary - positives) and that spams not caught have all values below 0. Maybe I am a non-typical email user?

And no, I don' want to disable the yellow range completely. I want to use it to show possible spams which got greylisted.

**Comment by friedPotat0** [comment]
You should not lower the greylisting range to zero. The way you use greylisting is exactly how it should be. But in fact the most uncertain value when it comes to spam classification of mail servers regardless of the greylisting is the interval around zero. As you already noticed: `many legitimate emails have values below 2`. But there can be spams in that range as well.

When you say that mails with values below zero are spams without any exception, which I doubt because of the aforementioned uncertainty of the classification, I would suggest you to set the score ranges to to following values:

- red: greater than 5
- yellow: between 0 and 5
- green: lower than 0

The way you interpret your scores around zero is an edge case which I might be handing when I rewrite most of the score range settings in the add-on options. I thought of something like a two handle range slider where you can drag the handles wherever you want. But there is more to consider when implementing this. The way it is done now with the input fields could result in overlapping ranges when I remove the zero value boundary and do not implement further exception handling.

**Comment by sphh** [comment]
Each to their own! ;-)

Thank you for your suggestion, but I guess I will keep my settings because they work well for me.

Obviously it should not be possible to set th green level higher than the red. Isn't it possible to link the lowest possible red level to the currently selected green level (and vice versa?)

I would not mind to change this in the advance configuration screen, if this is an edge case indeed. But I could not find the appropriate setting there …

**Comment by friedPotat0** [comment]
Your use case should be working in the next version. I removed the zero value boundary and catched the case when the red and green values overlap. So it should not be possible to break the ranges completely.

**Comment by sphh** [comment]
Thanks!

**Comment by sphh** [comment]
Thanks for implementing this!!
